jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com/heroku_4acd7d2b4bae48e?reconnect=true #change this to your database url
    password: 89f9e12fdedf9ad  #change this to your database Password
    username: b2a0416c627626 #change this to your database Username
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
